@startuml hallo
package game{
    abstract class Entity 
    class Globals
    class Manager
    class Obstacle
    class ObstacleManager
    abstract PhysikalEntity
    class Player
    class Scene

    Entity --|> PhysikalEntity
    Entity --|> Scene
    PhysikalEntity --|> Player
    PhysikalEntity --|> Obstacle

    Obstacle --* ObstacleManager

    Manager *-- ObstacleManager
    Manager *-- Player
    Manager *-- Scene
}


@enduml